[package]
name = "narui"
version = "0.1.0"
authors = ["Jaro Habiger <jarohabiger@googlemail.com>"]
edition = "2018"

[lib]
name = "narui"

[dependencies]
narui_derive = { path = "../narui_derive" }
lyon = "0.17.5"
stretch = { git = "https://github.com/vislyhq/stretch" }
winit = "0.24.0"
anyhow = "1.0.40"
lazy_static = "1.4.0"
vulkano = "0.22.0"
vulkano-shaders = "0.22.0"
vulkano-win = "0.22.0"
derivative = "2.2.0"
glyph_brush = "0.7.2"
notosans = "0.1.0"
palette = "0.5.0"
usvg = "0.14.1"

[profile.release]
debug = true
