dir_input:
  type: RawDirectoryReader
  file-pattern: test/*/tl-*.raw12
  width: 4096
  height: 3072

bitdepth_conv:
  type: BitDepthConverter
  input: <dir_input
cache:
  type: Cache
  input: <bitdepth_conv

display:
  type: BenchmarkSink
  input: <cache

display2:
  type: BenchmarkSink
  input: <cache

display3:
  type: BenchmarkSink
  input: <cache


# bench_sink:
#   type: BenchmarkSink
#   input: <bitdepth_conv
#     #
#     #     #bench_sink2:
#     #     #  type: BenchmarkSink
#     #     #  input: <dir_input
#     #     #
